### ISSUE TITLE
Help with editing the lua to make the player get a random rgb color from 0 to 2 without cycle

### ISSUE THREAD

**Issue by Auditormadness9** [VictorienXP/Rainbow-Player-Color-Cycle#1]
Hello. I play without a cycle but I'm trying to edit it so that it generates a random rgb color, where each time a player respawns the r,g and b roll a random value from the [0,2] interval. 

I tried simply editing the rgb locals into this

`local r = math.random(0,2)`
`local g = math.random(0,2)`
`local b = math.random(0,2)`

but that didn't seem to help. Instead it just started flickering my player color. Any suggestions? 

Thanks a lot in advance!

**Comment by VictorienXP** [comment]
I'll rework how the script work for better performance for your use case. Please stay tuned.

**Comment by VictorienXP** [comment]
Here you go @Auditormadness9 from the changes in 0a040fbcce0ff6c904dd8b1b0ef6ba0c0d6eef2e:
You just have to set `xp_rpcc_disable_cycle` to **1** and players will now have a static color that will change after death.

**Comment by VictorienXP** [comment]
Now if you really want a completely random color, the script is unfortunately not made for that but for a rainbow color effect. 
So you might need to edit the script heavily or play around with the `lightness` value.
https://github.com/VictorienXP/Rainbow-Player-Color-Cycle/blob/0a040fbcce0ff6c904dd8b1b0ef6ba0c0d6eef2e/lua/autorun/xp_rainbow_player_color_cycle.lua#L106-L115
`r`, `g` and `b` are calculated every frame so you cannot just put random values directly there as it will flicker as you experimented.

The `base_value` works in two ways, either cycle or static.
```lua
do_not_cycle and getBaseValue(v)		or		time * speed + offset
```
Basically `getBaseValue(v)` is called to get the saved static value if cycling is disabled.

https://github.com/VictorienXP/Rainbow-Player-Color-Cycle/blob/0a040fbcce0ff6c904dd8b1b0ef6ba0c0d6eef2e/lua/autorun/xp_rainbow_player_color_cycle.lua#L57-L59

This will give the saved value if any is present or will make one on the fly
https://github.com/VictorienXP/Rainbow-Player-Color-Cycle/blob/0a040fbcce0ff6c904dd8b1b0ef6ba0c0d6eef2e/lua/autorun/xp_rainbow_player_color_cycle.lua#L51-L55

The value is regenerated after every death here
https://github.com/VictorienXP/Rainbow-Player-Color-Cycle/blob/0a040fbcce0ff6c904dd8b1b0ef6ba0c0d6eef2e/lua/autorun/xp_rainbow_player_color_cycle.lua#L134
